version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.21.0
    platform: linux/amd64
    container_name: selenium-hub
    ports:
      - "4452:4442"
      - "4453:4443"
      - "4454:4444"

  patient-node:
    image: selenium/node-chrome:4.21.0
    platform: linux/amd64
    container_name: patient-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    # ports:
    #   - "7901:7900"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      # - SE_VNC_NO_PASSWORD=1

  provider-node:
    image: selenium/node-chrome:4.21.0
    platform: linux/amd64
    container_name: provider-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    # ports:
    #   - "7900:7900"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      # - SE_VNC_NO_PASSWORD=1

